modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "e418"
version = "${version}"
displayName = "Myths of Entity 418"
authors = "maxthetomas, CSQRB, iller_saver"
description = '''
A less intrusive horror mod inspired by Voices of the Void.
'''
#logoFile = ""

[[dependencies.e418]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.e418]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.e418]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "e418.mixins.json"
