modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "votvevents"
version = "${version}"
displayName = "votvevents"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.votvevents]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.votvevents]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.votvevents]]
modId = "architectury"
type = "required"
versionRange = "[15.0.3,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "votvevents.mixins.json"
